### ISSUE TITLE
error running ret-robust 

### ISSUE THREAD

**Issue by codecodebear** [RUC-NLPIR/FlashRAG#64]
Hello, 

When I run ```ret-robust``` approach using 

```
python run_exp.py --method_name 'ret-robust' \
                  --split 'test' \
                  --dataset_name 'nq' \
                  --gpu_id '0,1,2,3'
```
I also set ```single_hop``` to ```True``` inside of retrobust func in run_exp.py
```
pipeline = SelfAskPipeline(config, max_iter=5, single_hop=True)
```
----------------------------------------------------------------------------
I get this error below:
```
Inference:   0%|                                                                 | 0/3610 [00:05<?, ?it/s]
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/smalldog/FlashRAG/examples/methods/run_exp.py", line 495, in <module>
[rank0]:     func(args)
[rank0]:   File "/home/smalldog/FlashRAG/examples/methods/run_exp.py", line 248, in retrobust
[rank0]:     result = pipeline.run(test_data, pred_process_fun=selfask_pred_parse)
[rank0]:   File "/home/smalldog/FlashRAG/flashrag/pipeline/active_pipeline.py", line 893, in run
[rank0]:     self.run_item(item)
[rank0]:   File "/home/smalldog/FlashRAG/flashrag/pipeline/active_pipeline.py", line 831, in run_item
[rank0]:     + self.format_reference(retrieval_result)
[rank0]:   File "/home/smalldog/FlashRAG/flashrag/pipeline/active_pipeline.py", line 801, in format_reference
[rank0]:     content = doc_item["contents"]
[rank0]: TypeError: list indices must be integers or slices, not str
```

Based on the error message, the bug likely points to [this line](https://github.com/RUC-NLPIR/FlashRAG/blob/main/flashrag/pipeline/active_pipeline.py#L801).
Can you take a look? Thank you so much!

**Comment by ignorejjj** [comment]
Thank you for raising the question! This is a bug left behind earlier, and upon investigation, it was found that it is caused by the retrieval cache mechanism. This issue occurs when `save_trieval_cache` is set to True. I have fixed this bug in commit 18a727e58cbb42a10a5d62cc257e0917d0a5009d.

**Comment by codecodebear** [comment]
Hi,
Thank you for your reply and for addressing the bug! 

I met another bug (```Object of type float32 is not JSON serializable```) though:
```
Inference: 100%|████████████████████████████████████████████| 50/50 [00:24<00:00,  2.01it/s]
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/smalldog/FlashRAG/examples/methods/run_exp.py", line 553, in <module>
[rank0]:     func(args)
[rank0]:   File "/home/smalldog/FlashRAG/examples/methods/run_exp.py", line 248, in retrobust
[rank0]:     result = pipeline.run(test_data, pred_process_fun=selfask_pred_parse)
[rank0]:   File "/home/smalldog/FlashRAG/flashrag/pipeline/active_pipeline.py", line 895, in run
[rank0]:     dataset = self.evaluate(dataset, do_eval=do_eval, pred_process_fun=pred_process_fun)
[rank0]:   File "/home/smalldog/FlashRAG/flashrag/pipeline/pipeline.py", line 37, in evaluate
[rank0]:     eval_result = self.evaluator.evaluate(dataset)
[rank0]:   File "/home/smalldog/FlashRAG/flashrag/evaluator/evaluator.py", line 66, in evaluate
[rank0]:     self.save_data(data)
[rank0]:   File "/home/smalldog/FlashRAG/flashrag/evaluator/evaluator.py", line 82, in save_data
[rank0]:     data.save(save_path)
[rank0]:   File "/home/smalldog/FlashRAG/flashrag/dataset/dataset.py", line 164, in save
[rank0]:     json.dump(save_data, f, indent=4)
[rank0]:   File "/opt/conda/envs/flashrag-env-conda-4gpu/lib/python3.10/json/__init__.py", line 179, in dump
[rank0]:     for chunk in iterable:
[rank0]:   File "/opt/conda/envs/flashrag-env-conda-4gpu/lib/python3.10/json/encoder.py", line 429, in _iterencode
[rank0]:     yield from _iterencode_list(o, _current_indent_level)
[rank0]:   File "/opt/conda/envs/flashrag-env-conda-4gpu/lib/python3.10/json/encoder.py", line 325, in _iterencode_list
[rank0]:     yield from chunks
[rank0]:   File "/opt/conda/envs/flashrag-env-conda-4gpu/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
[rank0]:     yield from chunks
[rank0]:   File "/opt/conda/envs/flashrag-env-conda-4gpu/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
[rank0]:     yield from chunks
[rank0]:   File "/opt/conda/envs/flashrag-env-conda-4gpu/lib/python3.10/json/encoder.py", line 325, in _iterencode_list
[rank0]:     yield from chunks
[rank0]:   File "/opt/conda/envs/flashrag-env-conda-4gpu/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
[rank0]:     yield from chunks
[rank0]:   File "/opt/conda/envs/flashrag-env-conda-4gpu/lib/python3.10/json/encoder.py", line 438, in _iterencode
[rank0]:     o = _default(o)
[rank0]:   File "/opt/conda/envs/flashrag-env-conda-4gpu/lib/python3.10/json/encoder.py", line 179, in default
[rank0]:     raise TypeError(f'Object of type {o.__class__.__name__} '
[rank0]: TypeError: Object of type float32 is not JSON serializable
```

Can you take a look? Thank you!

**Comment by ignorejjj** [comment]
This bug has been fixed before. Are you using the latest code? From the GitHub code repository, it appears that the latest `dataset/dataset.py` contains only 160 lines, instead of the 164 lines in the error message.

**Comment by codecodebear** [comment]
Yes, I am using the latest code. I also cloned a fresh copy and the bug remains.
I add a str representation for the ```Item``` class, so ```dataset.py``` becomes 164 lines :)

**Comment by ignorejjj** [comment]
Thank you for your attempt. I have successfully reproduced the bug on my local machine and have fixed it (commit ca382cbded54e861e6e246aa39f53caba0843aaa).

**Comment by codecodebear** [comment]
Hi, thank you for fixing the bug! works now.
